import type {
  ActivityItem,
  Circle,
  CircleSummary,
  Division,
  DivisionSummary,
  DriverAssignment,
  DriverOwnershipHistoryItem,
  DriverRecord,
  FleetVehicle,
  FuelLogEntry,
  FuelOwnershipHistoryItem,
  LookupData,
  StatusHistoryItem,
  Substation,
  TransferRecord,
} from "@/lib/types";

const today = new Date();

function iso(offsetDays: number) {
  const date = new Date(today);
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString().slice(0, 10);
}

export const mockCircles: Circle[] = [
  {
    id: "circle-barabanki",
    name: "Barabanki",
    zone_id: "zone-central-up",
    state: "Uttar Pradesh",
    discom: "MVVNL",
    contract_ref: "EDC-BBK-FRT-2026",
  },
  {
    id: "circle-lucknow",
    name: "Lucknow",
    zone_id: "zone-central-up",
    state: "Uttar Pradesh",
    discom: "MVVNL",
    contract_ref: "EDC-LKO-FRT-2026",
  },
];

export const mockDivisions: Division[] = [
  { id: "division-barabanki", name: "Barabanki", circle_id: "circle-barabanki" },
  { id: "division-fatehpur", name: "Fatehpur", circle_id: "circle-barabanki" },
  { id: "division-haidergarh", name: "Haidergarh", circle_id: "circle-barabanki" },
  { id: "division-ramnagar", name: "Ramnagar", circle_id: "circle-barabanki" },
  { id: "division-ramsanehighat", name: "Ramsanehighat", circle_id: "circle-barabanki" },
  { id: "division-lucknow-city", name: "Lucknow City", circle_id: "circle-lucknow" },
];

export const mockSubstations: Substation[] = [
  { id: "ss-naka-satrikh", name: "Naka Satrikh", division_id: "division-barabanki" },
  { id: "ss-dewa-road", name: "Dewa Road", division_id: "division-barabanki" },
  { id: "ss-fatehpur-town", name: "Fatehpur Town", division_id: "division-fatehpur" },
  { id: "ss-belhara", name: "Belhara", division_id: "division-fatehpur" },
  { id: "ss-haidergarh-town", name: "Haidergarh Town", division_id: "division-haidergarh" },
  { id: "ss-trivediganj", name: "Trivediganj", division_id: "division-haidergarh" },
  { id: "ss-ramnagar-rural", name: "Ramnagar Rural", division_id: "division-ramnagar" },
  { id: "ss-mahadeva", name: "Mahadeva", division_id: "division-ramnagar" },
  { id: "ss-ramsanehighat-town", name: "Ramsanehighat Town", division_id: "division-ramsanehighat" },
  { id: "ss-dariyabad", name: "Dariyabad", division_id: "division-ramsanehighat" },
  { id: "ss-alambagh", name: "Alambagh", division_id: "division-lucknow-city" },
];

export const mockLookups: LookupData = {
  circles: mockCircles,
  divisions: mockDivisions,
  substations: mockSubstations,
};

export const mockVehicles: FleetVehicle[] = [
  {
    vehicle_id: "vehicle-up32-ab-1245",
    registration_no: "UP32 AB 1245",
    vehicle_type: "Bolero",
    fuel_type: "Diesel",
    fuel_ownership: "company",
    driver_ownership: "company",
    model_year: 2021,
    owner_name: "Rajesh Verma",
    owner_mobile: "9876543210",
    vendor_name: "Imperial Fleet Services",
    gps_company: "Airtel GPS",
    gps_device_id: "GPS-BBK-001",
    home_circle_id: "circle-barabanki",
    home_circle: "Barabanki",
    insurance_expiry: iso(80),
    fitness_expiry: iso(160),
    pollution_expiry: iso(25),
    status: "active",
    notes: "Primary FRT van for city feeder faults",
    assignment_id: "assignment-1",
    current_circle_id: "circle-barabanki",
    current_circle: "Barabanki",
    division_id: "division-barabanki",
    division: "Barabanki",
    substation_id: "ss-naka-satrikh",
    substation: "Naka Satrikh",
    assigned_from: iso(-40),
    assigned_by: "Circle Incharge",
  },
  {
    vehicle_id: "vehicle-up32-cd-8831",
    registration_no: "UP32 CD 8831",
    vehicle_type: "Pickup",
    fuel_type: "Diesel",
    fuel_ownership: "company",
    driver_ownership: "vendor",
    model_year: 2020,
    owner_name: "S K Motors",
    owner_mobile: "9876543211",
    vendor_name: "Imperial Fleet Services",
    gps_company: "Trackpoint",
    gps_device_id: "GPS-BBK-002",
    home_circle_id: "circle-barabanki",
    home_circle: "Barabanki",
    insurance_expiry: iso(18),
    fitness_expiry: iso(75),
    pollution_expiry: iso(9),
    status: "maintenance",
    notes: "Tyre replacement pending",
    assignment_id: "assignment-2",
    current_circle_id: "circle-barabanki",
    current_circle: "Barabanki",
    division_id: "division-fatehpur",
    division: "Fatehpur",
    substation_id: "ss-fatehpur-town",
    substation: "Fatehpur Town",
    assigned_from: iso(-32),
    assigned_by: "Division Incharge",
  },
  {
    vehicle_id: "vehicle-up41-af-5521",
    registration_no: "UP41 AF 5521",
    vehicle_type: "Bolero",
    fuel_type: "Diesel",
    fuel_ownership: "company",
    driver_ownership: "company",
    model_year: 2022,
    owner_name: "Amit Transport",
    owner_mobile: "9876543212",
    vendor_name: "Amit Transport",
    gps_company: "Airtel GPS",
    gps_device_id: "GPS-BBK-003",
    home_circle_id: "circle-barabanki",
    home_circle: "Barabanki",
    insurance_expiry: iso(210),
    fitness_expiry: iso(120),
    pollution_expiry: iso(42),
    status: "active",
    notes: null,
    assignment_id: "assignment-3",
    current_circle_id: "circle-barabanki",
    current_circle: "Barabanki",
    division_id: "division-haidergarh",
    division: "Haidergarh",
    substation_id: "ss-trivediganj",
    substation: "Trivediganj",
    assigned_from: iso(-27),
    assigned_by: "Circle Incharge",
  },
  {
    vehicle_id: "vehicle-up41-gh-7712",
    registration_no: "UP41 GH 7712",
    vehicle_type: "Scorpio",
    fuel_type: "Diesel",
    fuel_ownership: "company",
    driver_ownership: "company",
    model_year: 2019,
    owner_name: "Khan Associates",
    owner_mobile: "9876543213",
    vendor_name: "Khan Associates",
    gps_company: "Trackpoint",
    gps_device_id: "GPS-BBK-004",
    home_circle_id: "circle-barabanki",
    home_circle: "Barabanki",
    insurance_expiry: iso(-6),
    fitness_expiry: iso(22),
    pollution_expiry: iso(60),
    status: "breakdown",
    notes: "Engine inspection at workshop",
    assignment_id: "assignment-4",
    current_circle_id: "circle-barabanki",
    current_circle: "Barabanki",
    division_id: "division-ramnagar",
    division: "Ramnagar",
    substation_id: "ss-ramnagar-rural",
    substation: "Ramnagar Rural",
    assigned_from: iso(-11),
    assigned_by: "Division Incharge",
  },
  {
    vehicle_id: "vehicle-up32-jk-9088",
    registration_no: "UP32 JK 9088",
    vehicle_type: "Bolero",
    fuel_type: "Diesel",
    fuel_ownership: "company",
    driver_ownership: "company",
    model_year: 2023,
    owner_name: "Imperial Electric",
    owner_mobile: "9876543214",
    vendor_name: "Imperial Fleet Services",
    gps_company: "Airtel GPS",
    gps_device_id: "GPS-BBK-005",
    home_circle_id: "circle-barabanki",
    home_circle: "Barabanki",
    insurance_expiry: iso(365),
    fitness_expiry: iso(280),
    pollution_expiry: iso(130),
    status: "standby",
    notes: "Reserve van",
    assignment_id: "assignment-5",
    current_circle_id: "circle-barabanki",
    current_circle: "Barabanki",
    division_id: "division-ramsanehighat",
    division: "Ramsanehighat",
    substation_id: "ss-ramsanehighat-town",
    substation: "Ramsanehighat Town",
    assigned_from: iso(-5),
    assigned_by: "Circle Incharge",
  },
  {
    vehicle_id: "vehicle-up32-lk-4201",
    registration_no: "UP32 LK 4201",
    vehicle_type: "Bolero",
    fuel_type: "Diesel",
    fuel_ownership: "company",
    driver_ownership: "vendor",
    model_year: 2021,
    owner_name: "Lucknow Fleet Co.",
    owner_mobile: "9876543299",
    vendor_name: "Lucknow Fleet Co.",
    gps_company: "Airtel GPS",
    gps_device_id: "GPS-LKO-001",
    home_circle_id: "circle-lucknow",
    home_circle: "Lucknow",
    insurance_expiry: iso(44),
    fitness_expiry: iso(88),
    pollution_expiry: iso(12),
    status: "active",
    notes: "Demo cross-circle visibility sample",
    assignment_id: "assignment-6",
    current_circle_id: "circle-lucknow",
    current_circle: "Lucknow",
    division_id: "division-lucknow-city",
    division: "Lucknow City",
    substation_id: "ss-alambagh",
    substation: "Alambagh",
    assigned_from: iso(-14),
    assigned_by: "Zonal Manager",
  },
];

export const mockDrivers: DriverRecord[] = [
  {
    driver_id: "driver-ramesh",
    name: "Ramesh Yadav",
    mobile: "9450001001",
    license_no: "UP142026001",
    license_expiry: iso(320),
    address: "Barabanki",
    status: "active",
    circle_id: "circle-barabanki",
    circle: "Barabanki",
    vehicle_id: "vehicle-up32-ab-1245",
    registration_no: "UP32 AB 1245",
    shift: "shift_a",
    assigned_from: iso(-40),
  },
  {
    driver_id: "driver-sajid",
    name: "Sajid Ali",
    mobile: "9450001002",
    license_no: "UP142026002",
    license_expiry: iso(24),
    address: "Fatehpur",
    status: "active",
    circle_id: "circle-barabanki",
    circle: "Barabanki",
    vehicle_id: "vehicle-up32-ab-1245",
    registration_no: "UP32 AB 1245",
    shift: "shift_b",
    assigned_from: iso(-20),
  },
  {
    driver_id: "driver-mohan",
    name: "Mohan Singh",
    mobile: "9450001003",
    license_no: "UP142026003",
    license_expiry: iso(190),
    address: "Haidergarh",
    status: "active",
    circle_id: "circle-barabanki",
    circle: "Barabanki",
    vehicle_id: "vehicle-up41-af-5521",
    registration_no: "UP41 AF 5521",
    shift: "shift_a",
    assigned_from: iso(-27),
  },
  {
    driver_id: "driver-dinesh",
    name: "Dinesh Pal",
    mobile: "9450001004",
    license_no: "UP142026004",
    license_expiry: iso(-3),
    address: "Ramnagar",
    status: "active",
    circle_id: "circle-barabanki",
    circle: "Barabanki",
    vehicle_id: "vehicle-up41-gh-7712",
    registration_no: "UP41 GH 7712",
    shift: "shift_c",
    assigned_from: iso(-11),
  },
  {
    driver_id: "driver-virendra",
    name: "Virendra Kumar",
    mobile: "9450001005",
    license_no: "UP142026005",
    license_expiry: iso(88),
    address: "Ramsanehighat",
    status: "inactive",
    circle_id: "circle-barabanki",
    circle: "Barabanki",
    vehicle_id: null,
    registration_no: null,
    shift: null,
    assigned_from: null,
  },
];

export const mockTransfers: TransferRecord[] = [
  {
    id: "transfer-haidergarh-trivediganj",
    vehicle_id: "vehicle-up41-af-5521",
    registration_no: "UP41 AF 5521",
    transfer_date: iso(-27),
    reason: "Interchange",
    approved_by: "Circle Incharge",
    remarks: "Moved after feeder load review",
    is_cross_circle: false,
    from_circle_id: "circle-barabanki",
    from_circle: "Barabanki",
    from_division_id: "division-haidergarh",
    from_division: "Haidergarh",
    from_substation_id: "ss-haidergarh-town",
    from_substation: "Haidergarh Town",
    to_circle_id: "circle-barabanki",
    to_circle: "Barabanki",
    to_division_id: "division-haidergarh",
    to_division: "Haidergarh",
    to_substation_id: "ss-trivediganj",
    to_substation: "Trivediganj",
    created_at: iso(-27),
  },
  {
    id: "transfer-lucknow-demo",
    vehicle_id: "vehicle-up32-lk-4201",
    registration_no: "UP32 LK 4201",
    transfer_date: iso(-14),
    reason: "Cross-Circle",
    approved_by: "Zonal Manager",
    remarks: "Demo record for HQ report",
    is_cross_circle: true,
    from_circle_id: "circle-barabanki",
    from_circle: "Barabanki",
    from_division_id: "division-barabanki",
    from_division: "Barabanki",
    from_substation_id: "ss-dewa-road",
    from_substation: "Dewa Road",
    to_circle_id: "circle-lucknow",
    to_circle: "Lucknow",
    to_division_id: "division-lucknow-city",
    to_division: "Lucknow City",
    to_substation_id: "ss-alambagh",
    to_substation: "Alambagh",
    created_at: iso(-14),
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: "activity-transfer-lucknow-demo",
    activity_type: "transfer",
    created_at: `${iso(-14)}T10:30:00+05:30`,
    vehicle_id: "vehicle-up32-lk-4201",
    registration_no: "UP32 LK 4201",
    circle_id: "circle-lucknow",
    division_id: "division-lucknow-city",
    description: "Barabanki / Dewa Road to Lucknow / Alambagh",
  },
  {
    id: "activity-status-breakdown",
    activity_type: "status",
    created_at: `${iso(-6)}T12:15:00+05:30`,
    vehicle_id: "vehicle-up41-gh-7712",
    registration_no: "UP41 GH 7712",
    circle_id: "circle-barabanki",
    division_id: "division-ramnagar",
    description: "Status changed to breakdown: Engine inspection at workshop",
  },
  {
    id: "activity-transfer-haidergarh",
    activity_type: "transfer",
    created_at: `${iso(-27)}T09:00:00+05:30`,
    vehicle_id: "vehicle-up41-af-5521",
    registration_no: "UP41 AF 5521",
    circle_id: "circle-barabanki",
    division_id: "division-haidergarh",
    description: "Haidergarh / Haidergarh Town to Haidergarh / Trivediganj",
  },
];

export const mockDriverAssignments: DriverAssignment[] = [
  {
    id: "driver-assignment-1",
    vehicle_id: "vehicle-up32-ab-1245",
    driver_id: "driver-ramesh",
    driver_name: "Ramesh Yadav",
    mobile: "9450001001",
    license_no: "UP142026001",
    shift: "shift_a",
    from_date: iso(-40),
    to_date: null,
    remarks: "Shift A duty",
  },
  {
    id: "driver-assignment-2",
    vehicle_id: "vehicle-up32-ab-1245",
    driver_id: "driver-sajid",
    driver_name: "Sajid Ali",
    mobile: "9450001002",
    license_no: "UP142026002",
    shift: "shift_b",
    from_date: iso(-20),
    to_date: null,
    remarks: "Shift B feeder duty",
  },
  {
    id: "driver-assignment-3",
    vehicle_id: "vehicle-up41-af-5521",
    driver_id: "driver-mohan",
    driver_name: "Mohan Singh",
    mobile: "9450001003",
    license_no: "UP142026003",
    shift: "shift_a",
    from_date: iso(-27),
    to_date: null,
    remarks: null,
  },
  {
    id: "driver-assignment-4",
    vehicle_id: "vehicle-up41-gh-7712",
    driver_id: "driver-dinesh",
    driver_name: "Dinesh Pal",
    mobile: "9450001004",
    license_no: "UP142026004",
    shift: "shift_c",
    from_date: iso(-11),
    to_date: null,
    remarks: "Shift C emergency duty",
  },
];

export const mockFuelOwnershipHistory: FuelOwnershipHistoryItem[] = [
  {
    id: "fuel-history-1",
    vehicle_id: "vehicle-up32-ab-1245",
    ownership: "company",
    from_date: iso(-90),
    to_date: null,
    remarks: "Initial — company fuel",
    changed_by: "System",
  },
];

export const mockDriverOwnershipHistory: DriverOwnershipHistoryItem[] = [
  {
    id: "driver-ownership-history-1",
    vehicle_id: "vehicle-up32-ab-1245",
    ownership: "company",
    from_date: iso(-90),
    to_date: null,
    remarks: "Initial — company driver",
    changed_by: "System",
  },
  {
    id: "driver-ownership-history-2",
    vehicle_id: "vehicle-up32-cd-8831",
    ownership: "vendor",
    from_date: iso(-60),
    to_date: null,
    remarks: "Driver supplied by vendor",
    changed_by: "System",
  },
];

export const mockStatusHistory: StatusHistoryItem[] = [
  {
    id: "status-1",
    vehicle_id: "vehicle-up32-ab-1245",
    status: "active",
    remarks: "Initial deployment",
    from_date: iso(-40),
    to_date: null,
    recorded_by: "System Seed",
  },
  {
    id: "status-2",
    vehicle_id: "vehicle-up32-cd-8831",
    status: "maintenance",
    remarks: "Tyre replacement pending",
    from_date: iso(-7),
    to_date: null,
    recorded_by: "Division Incharge",
  },
  {
    id: "status-3",
    vehicle_id: "vehicle-up41-gh-7712",
    status: "breakdown",
    remarks: "Engine inspection at workshop",
    from_date: iso(-6),
    to_date: null,
    recorded_by: "Division Incharge",
  },
];

export const mockFuelLogs: FuelLogEntry[] = [
  // up32-ab-1245: two fills. First (oldest) has no prior fill → no GPS segment.
  {
    id: "fuel-log-2",
    vehicle_id: "vehicle-up32-ab-1245",
    log_date: iso(-18),
    fuel_type: "Diesel",
    fuel_litres: 35,
    fuel_amount: 3150,
    gps_distance_km: null,
    gps_synced_at: null,
    recorded_by: "Circle Incharge",
    notes: "Tank topped up before inspection",
    created_at: iso(-18),
  },
  {
    id: "fuel-log-1",
    vehicle_id: "vehicle-up32-ab-1245",
    log_date: iso(-3),
    fuel_type: "Diesel",
    fuel_litres: 40,
    fuel_amount: 3600,
    gps_distance_km: 400, // 400 km / 40 L = 10 km/L
    gps_synced_at: iso(-1),
    recorded_by: "Circle Incharge",
    notes: null,
    created_at: iso(-3),
  },
  // up32-cd-8831: single fill → no segment yet
  {
    id: "fuel-log-3",
    vehicle_id: "vehicle-up32-cd-8831",
    log_date: iso(-5),
    fuel_type: "Diesel",
    fuel_litres: 50,
    fuel_amount: 4500,
    gps_distance_km: null,
    gps_synced_at: null,
    recorded_by: "Division Incharge",
    notes: "Monthly fill",
    created_at: iso(-5),
  },
  // up41-af-5521: two fills
  {
    id: "fuel-log-5",
    vehicle_id: "vehicle-up41-af-5521",
    log_date: iso(-22),
    fuel_type: "Diesel",
    fuel_litres: 42,
    fuel_amount: 3780,
    gps_distance_km: null,
    gps_synced_at: null,
    recorded_by: "Circle Incharge",
    notes: null,
    created_at: iso(-22),
  },
  {
    id: "fuel-log-4",
    vehicle_id: "vehicle-up41-af-5521",
    log_date: iso(-7),
    fuel_type: "Diesel",
    fuel_litres: 45,
    fuel_amount: 4050,
    gps_distance_km: 405, // 405 km / 45 L = 9 km/L
    gps_synced_at: iso(-1),
    recorded_by: "Circle Incharge",
    notes: null,
    created_at: iso(-7),
  },
];

export function buildCircleSummaries(vehicles = mockVehicles): CircleSummary[] {
  return mockCircles.map((circle) => {
    const rows = vehicles.filter((vehicle) => vehicle.home_circle_id === circle.id && vehicle.status !== "removed");
    return {
      circle_id: circle.id,
      circle: circle.name,
      total: rows.length,
      active: rows.filter((row) => row.status === "active").length,
      maintenance: rows.filter((row) => row.status === "maintenance").length,
      breakdown: rows.filter((row) => row.status === "breakdown").length,
      standby: rows.filter((row) => row.status === "standby").length,
      documents_expiring: rows.filter((row) =>
        [row.insurance_expiry, row.fitness_expiry, row.pollution_expiry].some((date) => {
          if (!date) return false;
          const days = Math.ceil((new Date(date).getTime() - today.getTime()) / 86400000);
          return days <= 30;
        }),
      ).length,
    };
  });
}

export function buildDivisionSummaries(vehicles = mockVehicles): DivisionSummary[] {
  return mockDivisions.map((division) => {
    const circle = mockCircles.find((item) => item.id === division.circle_id);
    const rows = vehicles.filter((vehicle) => vehicle.division_id === division.id && vehicle.status !== "removed");
    return {
      circle_id: division.circle_id,
      circle: circle?.name ?? "Unknown",
      division_id: division.id,
      division: division.name,
      total: rows.length,
      active: rows.filter((row) => row.status === "active").length,
      maintenance: rows.filter((row) => row.status === "maintenance").length,
      breakdown: rows.filter((row) => row.status === "breakdown").length,
      standby: rows.filter((row) => row.status === "standby").length,
    };
  });
}

